export const GLOBAL_CONSTANT = {
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  APP_URL: "http://localhost:5000/",
  TOKEN: "TOKEN",
  AUTH: "AUTH",
  ALERT: "ALERT",
  POST_CREATE: "POST_CREATE",
  POSTS: " POSTS",
  DELETE_POSTS: "DELETE_POSTS",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY: "CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT: "PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ROLE: "ROLE",
  ROLE_CREATE: "ROLE_CREATE",
  DELETE_ROLE: "DELETE_ROLE",
  SETTING_CREATE: "SETTING_CREATE",
  SETTING: "SETTING",
  DELETE_SETTING: "DELETE_SETTING",
  BASE_URL: "http://localhost:5000/",
};
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_ERROR = "REQUEST_ERROR";

export const DeleteData = (data, id) => {
  const newData = data.filter((d) => d._id !== id);
  return newData;
};
