import React from 'react';
import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
const Adminlayout = (props) => {
  return (
    <>
      
      <Head>
      <title>Responsive Side</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pro.ico" /> 
      </Head> 
      <div className="">
        <SideNavbar />
        <div className="main-div">
            {props.children}
        </div>
        </div>
    </>
  )
}

export default Adminlayout
